<a href="https://colab.research.google.com/github/yyred-max/Analisis_Data_Eksploratif/blob/main/Pertemuan_6%267_Yuliana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df1SE=pd.DataFrame({'StudentID':[9, 11, 13, 15, 17, 19, 21, 23, 25, 27,29],'ScoreSE':[22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]})
df2SE=pd.DataFrame({'StudentID':[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22,24, 26, 28, 30],'ScoreSE':[98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56,77, 33, 56, 27]})
df1ML=pd.DataFrame({'StudentID':[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,23, 25, 27, 29],'ScoreML':[39, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86,82, 92, 23, 49]})
df2ML=pd.DataFrame({'StudentID':[2, 4, 6, 8, 10, 12, 14, 16, 18, 20],'ScoreML':[93, 44, 78, 97, 87, 89, 39, 43, 88, 78]})
#Option1
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)
df1 = pd.concat([dfML, dfSE], axis=1)
df1
# df11 = pd.concat([dfML, dfSE], ignore_index=True)
# df11

    StudentID  ScoreML  StudentID  ScoreSE
0         1.0     39.0          9       22
1         3.0     49.0         11       66
2         5.0     55.0         13       31
3         7.0     77.0         15       51
4         9.0     52.0         17       71
5        11.0     86.0         19       91
6        13.0     41.0         21       56
7        15.0     77.0         23       32
8        17.0     73.0         25       52
9        19.0     51.0         27       73
10       21.0     86.0         29       92
11       23.0     82.0          2       98
12       25.0     92.0          4       93
13       27.0     23.0          6       44
14       29.0     49.0          8       77
15        2.0     93.0         10       69
16        4.0     44.0         12       56
17        6.0     78.0         14       31
18        8.0     97.0         16       53
19       10.0     87.0         18       78
20       12.0     89.0         20       93
21       14.0     39.0         22       56
22       16.0     43.0         24       77
23       18.0     88.0         26       33
24       20.0     78.0         28       56
25        NaN      NaN         30       27

In [ ]:
#Opsion 2
df2 = dfML.merge(dfSE,how='inner')
df2

    StudentID  ScoreML  ScoreSE
0           9       52       22
1          11       86       66
2          13       41       31
3          15       77       51
4          17       73       71
5          19       51       91
6          21       86       56
7          23       82       32
8          25       92       52
9          27       23       73
10         29       49       92
11          2       93       98
12          4       44       93
13          6       78       44
14          8       97       77
15         10       87       69
16         12       89       56
17         14       39       31
18         16       43       53
19         18       88       78
20         20       78       93

In [ ]:
df3 = dfML.merge(dfSE, how='left')
df3

    StudentID  ScoreML  ScoreSE
0           1       39      NaN
1           3       49      NaN
2           5       55      NaN
3           7       77      NaN
4           9       52     22.0
5          11       86     66.0
6          13       41     31.0
7          15       77     51.0
8          17       73     71.0
9          19       51     91.0
10         21       86     56.0
11         23       82     32.0
12         25       92     52.0
13         27       23     73.0
14         29       49     92.0
15          2       93     98.0
16          4       44     93.0
17          6       78     44.0
18          8       97     77.0
19         10       87     69.0
20         12       89     56.0
21         14       39     31.0
22         16       43     53.0
23         18       88     78.0
24         20       78     93.0

In [ ]:
df4 = dfML.merge(dfSE, how='right')
df4

    StudentID  ScoreML  ScoreSE
0           9     52.0       22
1          11     86.0       66
2          13     41.0       31
3          15     77.0       51
4          17     73.0       71
5          19     51.0       91
6          21     86.0       56
7          23     82.0       32
8          25     92.0       52
9          27     23.0       73
10         29     49.0       92
11          2     93.0       98
12          4     44.0       93
13          6     78.0       44
14          8     97.0       77
15         10     87.0       69
16         12     89.0       56
17         14     39.0       31
18         16     43.0       53
19         18     88.0       78
20         20     78.0       93
21         22      NaN       56
22         24      NaN       77
23         26      NaN       33
24         28      NaN       56
25         30      NaN       27

In [ ]:
df5 = dfML.merge(dfSE, how='outer')
df5

    StudentID  ScoreML  ScoreSE
0           1     39.0      NaN
1           2     93.0     98.0
2           3     49.0      NaN
3           4     44.0     93.0
4           5     55.0      NaN
5           6     78.0     44.0
6           7     77.0      NaN
7           8     97.0     77.0
8           9     52.0     22.0
9          10     87.0     69.0
10         11     86.0     66.0
11         12     89.0     56.0
12         13     41.0     31.0
13         14     39.0     31.0
14         15     77.0     51.0
15         16     43.0     53.0
16         17     73.0     71.0
17         18     88.0     78.0
18         19     51.0     91.0
19         20     78.0     93.0
20         21     86.0     56.0
21         22      NaN     56.0
22         23     82.0     32.0
23         24      NaN     77.0
24         25     92.0     52.0
25         26      NaN     33.0
26         27     23.0     73.0
27         28      NaN     56.0
28         29     49.0     92.0
29         30      NaN     27.0

MERGIN ON INDEX

In [ ]:
#Buat dataFrame
left1=pd.DataFrame({'key':['apple', 'ball', 'apple', 'apple', 'ball', 'cat'], 'value':range(6)})
right1=pd.DataFrame({'group_val': [33.4,5.0]}, index=['apple', 'ball'])
print(left1)
print()
print(right1)

     key  value
0  apple      0
1   ball      1
2  apple      2
3  apple      3
4   ball      4
5    cat      5

       group_val
apple       33.4
ball         5.0

In [ ]:
df1=pd.merge(left1, right1, left_on='key', right_index=True)
df1

     key  value  group_val
0  apple      0       33.4
1   ball      1        5.0
2  apple      2       33.4
3  apple      3       33.4
4   ball      4        5.0

In [ ]:
df2=pd.merge(left1, right1, left_on='key', right_index=True, how='outer')
df2

PESHAPING AND PIVOTING

In [ ]:
import numpy as np
data=np.arange(15).reshape((3,5))
indexers=['Rainfall', 'Humidity', 'Wind']
dframe1=pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [ ]:
stacked=dframe1.stack()
stacked

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [ ]:
stacked.unstack()

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

TEKNIK TRANSFORMASI

In [ ]:
import pandas as pd
frame3 = pd.DataFrame({'column 1': ['Looping'] * 3 + ['unctions']* 4,
                       'column 2': [10, 10, 22, 23, 23, 24, 24]})
frame3

   column 1  column 2
0   Looping        10
1   Looping        10
2   Looping        22
3  unctions        23
4  unctions        23
5  unctions        24
6  unctions        24

In [ ]:
frame3.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [ ]:
frame4 = frame3.drop_duplicates()
frame4

   column 1  column 2
0   Looping        10
2   Looping        22
3  unctions        23
5  unctions        24

In [ ]:
frame3['column 3'] = range(7)
frame3

   column 1  column 2  column 3
0   Looping        10         0
1   Looping        10         1
2   Looping        22         2
3  unctions        23         3
4  unctions        23         4
5  unctions        24         5
6  unctions        24         6

In [ ]:
frame5 = frame3.drop_duplicates(['column 2'])
frame5

   column 1  column 2  column 3
0   Looping        10         0
2   Looping        22         2
3  unctions        23         3
5  unctions        24         5

In [ ]:
ganti = frame5.replace(to_replace=10, value='kamu')
ganti

   column 1 column 2  column 3
0   Looping     kamu         0
2   Looping       22         2
3  unctions       23         3
5  unctions       24         5

In [ ]:
#Anda tambahkan satu kolom baru dari dataframe "ganti" dengan isian string
#Syaratnya buat isian yang ada data duplikat dikolom baru tersebut
#Hapus duplikat datanya

ganti['column 4'] = ['Mawar', 'Mawar', 'Melati', 'Harimau']
ganti

   column 1 column 2  column 3 column 4
0   Looping     kamu         0    Mawar
2   Looping       22         2    Mawar
3  unctions       23         3   Melati
5  unctions       24         5  Harimau

In [ ]:
ganti1 = ganti.drop_duplicates(['column 4'])
ganti1

   column 1 column 2  column 3 column 4
0   Looping     kamu         0    Mawar
3  unctions       23         3   Melati
5  unctions       24         5  Harimau

REPLACE

In [ ]:
import numpy as np
replaceFrame = pd.DataFrame({'column 1': [2, 3, -7, 3, 2, 4, -7, 3, 3], 'column 2': range(9)})
replaceFrame.replace(to_replace = -7, value = np.nan)

   column 1  column 2
0       2.0         0
1       3.0         1
2       NaN         2
3       3.0         3
4       2.0         4
5       4.0         5
6       NaN         6
7       3.0         7
8       3.0         8

In [ ]:
replaceFrame = pd.DataFrame({'column 1': [2, 3, -7, 3, 2, 4, -7, 3, 3], 'column 2': range(9)})
replaceFrame.replace(to_replace = [-7, 0], value = [np.nan, 'Nol'])

   column 1 column 2
0       2.0      Nol
1       3.0        1
2       NaN        2
3       3.0        3
4       2.0        4
5       4.0        5
6       NaN        6
7       3.0        7
8       3.0        8

HANDLING DATA

In [ ]:
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index =['apple', 'banana', 'kiwi', 'grapes', 'mango'],
                   columns = ['store1', 'store2', 'store3'])
dfx

        store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

In [ ]:
dfx['store4'] = np.nan
dfx.loc['watermelon'] = np.arange(15, 19)
dfx.loc['oranges'] = np.nan
dfx['store5'] = np.nan
dfx['store4']['apple'] = 20.
dfx

/tmp/ipykernel_7322/3731161268.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['store4']['apple'] = 20.

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

NAN Values in Pandas Object

In [ ]:
dfx.isnull()

            store1  store2  store3  store4  store5
apple        False   False   False   False    True
banana       False   False   False    True    True
kiwi         False   False   False    True    True
grapes       False   False   False    True    True
mango        False   False   False    True    True
watermelon   False   False   False   False    True
oranges       True    True    True    True    True

In [ ]:
dfx.notnull()

            store1  store2  store3  store4  store5
apple         True    True    True    True   False
banana        True    True    True   False   False
kiwi          True    True    True   False   False
grapes        True    True    True   False   False
mango         True    True    True   False   False
watermelon    True    True    True    True   False
oranges      False   False   False   False   False

In [ ]:
dfx.isnull().sum()

store1    1
store2    1
store3    1
store4    5
store5    7
dtype: int64

In [ ]:
#DROPPING BY ROW
dfx.dropna(how='all')

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN

In [ ]:
#DROPPING BY COLUMNS
dfx.dropna(how='all', axis=1)

            store1  store2  store3  store4
apple         15.0    16.0    17.0    20.0
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
watermelon    15.0    16.0    17.0    18.0
oranges        NaN     NaN     NaN     NaN